
#This is the general config of ModularVoiceChat
[generalconfig]
	#The vocal-server port
	#Range: > 0
	port = 7656
	#This field is optionnal, but may correct some issue with connecting to voice-server!
	#By providing an given hostname you are assured that all players use the same.
	forcedHostname = ""
	#Define if the micro on the speaking-players will be rendered.
	showWhoSpeak = false

	#The used voice-dispatcher
	[generalconfig.dispatcher]
		#The DispatchType
		# - "distanced" for a distance-based voice-dispatch
		# - "global" for a global, to all players, voice-dispatch
		dispatchType = "distanced"
		#If DispatchType is "distanced":
		#If true, the sound will fade-out with the distance
		fadeOut = true
		#If DispatchType is "distanced", it will be the max-distance that a player can hear another one.
		#Range: > 0
		maxDistance = 15

